; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

PUBLIC	?find_function@native@@YAPEAXPEAXI@Z		; native::find_function
PUBLIC	??$r_hash@D@@YAIPEAD@Z				; r_hash<char>
PUBLIC	main

; Function compile flags: /Ogspy
PUBLIC  AlignRSP
_TEXT SEGMENT
	AlignRSP PROC
	push rsi; Preserve RSI since we're stomping on it
	mov  rsi, rsp; Save the value of RSP so it can be restored
	and  rsp, 0FFFFFFFFFFFFFFF0h; Align RSP to 16 bytes
	sub  rsp, 020h; Allocate homing space for ExecutePayload
	call main; Call the entry point of the payload
	mov  rsp, rsi; Restore the original value of RSP
	pop  rsi; Restore RSI
	ret; Return to caller
	AlignRSP ENDP
_TEXT ENDS

_TEXT	SEGMENT
main	PROC
; File E:\projects\_playground_\shellcode-test\shellcode-test\main.cpp
; Line 10
$LN16:
	sub	rsp, 40					; 00000028H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 45
	mov	rax, QWORD PTR gs:[96]
	mov	rcx, QWORD PTR [rax+24]
	mov	rax, QWORD PTR [rcx+16]
; Line 52
	xor	ecx, ecx
	mov	r8, rax
$LL6@main:
; Line 56
	mov	rdx, QWORD PTR [rax+96]
	cmp	WORD PTR [rdx], 75			; 0000004bH
	jne	SHORT $LN13@main
	cmp	WORD PTR [rdx+16], 46			; 0000002eH
	je	SHORT $LN11@main
$LN13@main:
; Line 61
	mov	rax, QWORD PTR [rax]
; Line 63
	test	rax, rax
	je	SHORT $LN3@main
	cmp	rax, r8
	je	SHORT $LN3@main
	jmp	SHORT $LL6@main
$LN11@main:
; Line 59
	mov	rcx, QWORD PTR [rax+48]
$LN3@main:
; File E:\projects\_playground_\shellcode-test\shellcode-test\main.cpp
; Line 16
	mov	edx, 1723602811				; 66bc177bH
	call	?find_function@native@@YAPEAXPEAXI@Z	; native::find_function
; Line 19
	CALL after_$SG92202
$SG92202 DB	'user32.dll', 00H
	ORG $+1
after_$SG92202:
	POP  rcx

; 	lea	rcx, OFFSET FLAT:$SG92202
	call	rax
	mov	rcx, rax
	mov	edx, 1844401716				; 6def5634H
	call	?find_function@native@@YAPEAXPEAXI@Z	; native::find_function
; Line 22
	xor	r9d, r9d
	CALL after_$SG92203
$SG92203 DB	'bar', 00H
after_$SG92203:
	POP  r8

; 	lea	r8, OFFSET FLAT:$SG92203
	CALL after_$SG92204
$SG92204 DB	'foo', 00H
after_$SG92204:
	POP  rdx

; 	lea	rdx, OFFSET FLAT:$SG92204
	xor	ecx, ecx
	call	rax
; Line 23
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@D@@YAIPEAD@Z
_TEXT	SEGMENT
str$ = 48
??$r_hash@D@@YAIPEAD@Z PROC				; r_hash<char>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 17
$LN6:
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 18
	cmp	BYTE PTR [rcx], 0
	mov	rbx, rcx
	je	SHORT $LN3@r_hash
	inc	rcx
	call	??$r_hash@D@@YAIPEAD@Z			; r_hash<char>
	imul	edx, eax, 33				; 00000021H
	movsx	eax, BYTE PTR [rbx]
	add	eax, edx
	jmp	SHORT $LN4@r_hash
$LN3@r_hash:
	mov	eax, 5381				; 00001505H
$LN4@r_hash:
; Line 19
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??$r_hash@D@@YAIPEAD@Z ENDP				; r_hash<char>
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_function@native@@YAPEAXPEAXI@Z
_TEXT	SEGMENT
mod$ = 64
hash$ = 72
?find_function@native@@YAPEAXPEAXI@Z PROC		; native::find_function, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 69
$LN13:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	push	r14
	push	r15
	sub	rsp, 32					; 00000020H
; Line 72
	movsxd	rax, DWORD PTR [rcx+60]
; Line 79
	xor	esi, esi
	mov	r15d, edx
	mov	rbx, rcx
	mov	edi, DWORD PTR [rax+rcx+136]
	add	rdi, rcx
	cmp	DWORD PTR [rdi+24], esi
	jbe	SHORT $LN3@find_funct
	mov	r14d, DWORD PTR [rdi+32]
$LL4@find_funct:
; Line 82
	lea	rax, QWORD PTR [r14+rsi*4]
; Line 85
	mov	ecx, DWORD PTR [rax+rbx]
	add	rcx, rbx
	call	??$r_hash@D@@YAIPEAD@Z			; r_hash<char>
	cmp	eax, r15d
	je	SHORT $LN8@find_funct
; Line 79
	inc	esi
	cmp	esi, DWORD PTR [rdi+24]
	jb	SHORT $LL4@find_funct
$LN3@find_funct:
; Line 96
	xor	eax, eax
$LN1@find_funct:
; Line 97
	mov	rbx, QWORD PTR [rsp+64]
	mov	rbp, QWORD PTR [rsp+72]
	mov	rsi, QWORD PTR [rsp+80]
	add	rsp, 32					; 00000020H
	pop	r15
	pop	r14
	pop	rdi
	ret	0
$LN8@find_funct:
; Line 88
	mov	ecx, DWORD PTR [rdi+36]
	add	rcx, rbx
; Line 89
	movzx	edx, WORD PTR [rcx+rsi*2]
	mov	ecx, DWORD PTR [rdi+28]
	add	rcx, rbx
; Line 92
	mov	eax, DWORD PTR [rcx+rdx*4]
	add	rax, rbx
	jmp	SHORT $LN1@find_funct
?find_function@native@@YAPEAXPEAXI@Z ENDP		; native::find_function
_TEXT	ENDS
END
