; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31328.0 

	TITLE	E:\projects\_playground_\shellcode-test\shellcode-test\winexec.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG91944 DB	'calc', 00H
CONST	ENDS
PUBLIC	?get_peb@native@@YAPAU_PEB@1@XZ			; native::get_peb
PUBLIC	?find_module@native@@YAPAXI@Z			; native::find_module
PUBLIC	??$r_hash@_W@@YAIPA_W@Z				; r_hash<wchar_t>
PUBLIC	?find_kernel32@native@@YAPAXXZ			; native::find_kernel32
PUBLIC	?find_function@native@@YAPAXPAXI@Z		; native::find_function
PUBLIC	??$r_hash@D@@YAIPAD@Z				; r_hash<char>
PUBLIC	_main
; Function compile flags: /Ogspy
_TEXT	SEGMENT
_main	PROC
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 13
	mov	eax, DWORD PTR fs:48
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	push	698766968				; 29a65678H
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 69
	mov	eax, DWORD PTR [eax+12]
	mov	eax, DWORD PTR [eax+20]
	mov	eax, DWORD PTR [eax]
; File E:\projects\_playground_\shellcode-test\shellcode-test\winexec.cpp
; Line 16
	mov	eax, DWORD PTR [eax]
	push	DWORD PTR [eax+32]
	call	?find_function@native@@YAPAXPAXI@Z	; native::find_function
	pop	ecx
	pop	ecx
; Line 18
	push	0
	push	OFFSET $SG91944
	call	eax
; Line 19
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@D@@YAIPAD@Z
_TEXT	SEGMENT
_str$ = 8						; size = 4
??$r_hash@D@@YAIPAD@Z PROC				; r_hash<char>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 22
	mov	ecx, DWORD PTR _str$[esp-4]
	mov	eax, 5381				; 00001505H
	jmp	SHORT $LN10@r_hash
$LL2@r_hash:
; Line 23
	imul	eax, eax, 33
	add	eax, edx
$LN10@r_hash:
; Line 22
	movsx	edx, BYTE PTR [ecx]
	inc	ecx
	test	edx, edx
	jne	SHORT $LL2@r_hash
; Line 25
	ret	0
??$r_hash@D@@YAIPAD@Z ENDP				; r_hash<char>
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_function@native@@YAPAXPAXI@Z
_TEXT	SEGMENT
_mod$ = 8						; size = 4
_hash$ = 12						; size = 4
?find_function@native@@YAPAXPAXI@Z PROC			; native::find_function, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 76
	push	ebx
	push	ebp
	push	esi
; Line 83
	mov	esi, DWORD PTR _mod$[esp+8]
; Line 86
	xor	ebp, ebp
	push	edi
	mov	eax, DWORD PTR [esi+60]
	mov	edi, DWORD PTR [eax+esi+120]
	add	edi, esi
	cmp	DWORD PTR [edi+24], ebp
	jbe	SHORT $LN3@find_funct
; Line 89
	mov	ebx, DWORD PTR [edi+32]
	add	ebx, esi
$LL4@find_funct:
; Line 92
	mov	eax, DWORD PTR [ebx]
	add	eax, esi
	push	eax
	call	??$r_hash@D@@YAIPAD@Z			; r_hash<char>
	pop	ecx
	cmp	eax, DWORD PTR _hash$[esp+12]
	je	SHORT $LN8@find_funct
; Line 86
	inc	ebp
	add	ebx, 4
	cmp	ebp, DWORD PTR [edi+24]
	jb	SHORT $LL4@find_funct
$LN3@find_funct:
; Line 103
	xor	eax, eax
$LN1@find_funct:
	pop	edi
; Line 104
	pop	esi
	pop	ebp
	pop	ebx
	ret	0
$LN8@find_funct:
; Line 95
	mov	eax, DWORD PTR [edi+36]
	lea	eax, DWORD PTR [eax+ebp*2]
; Line 96
	movzx	ecx, WORD PTR [eax+esi]
	mov	eax, DWORD PTR [edi+28]
	lea	eax, DWORD PTR [eax+ecx*4]
; Line 99
	mov	eax, DWORD PTR [eax+esi]
	add	eax, esi
	jmp	SHORT $LN1@find_funct
?find_function@native@@YAPAXPAXI@Z ENDP			; native::find_function
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?find_kernel32@native@@YAPAXXZ
_TEXT	SEGMENT
?find_kernel32@native@@YAPAXXZ PROC			; native::find_kernel32, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 13
	mov	eax, DWORD PTR fs:48
; Line 69
	mov	eax, DWORD PTR [eax+12]
	mov	eax, DWORD PTR [eax+20]
	mov	eax, DWORD PTR [eax]
; Line 72
	mov	eax, DWORD PTR [eax]
	mov	eax, DWORD PTR [eax+32]
; Line 73
	ret	0
?find_kernel32@native@@YAPAXXZ ENDP			; native::find_kernel32
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ??$r_hash@_W@@YAIPA_W@Z
_TEXT	SEGMENT
_str$ = 8						; size = 4
??$r_hash@_W@@YAIPA_W@Z PROC				; r_hash<wchar_t>, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\hash.h
; Line 22
	mov	ecx, DWORD PTR _str$[esp-4]
	mov	eax, 5381				; 00001505H
	movzx	edx, WORD PTR [ecx]
	add	ecx, 2
	jmp	SHORT $LN9@r_hash
$LL2@r_hash:
; Line 23
	imul	eax, eax, 33
	add	eax, edx
	movzx	edx, WORD PTR [ecx]
	lea	ecx, DWORD PTR [ecx+2]
$LN9@r_hash:
; Line 22
	test	edx, edx
	jne	SHORT $LL2@r_hash
; Line 25
	ret	0
??$r_hash@_W@@YAIPA_W@Z ENDP				; r_hash<wchar_t>
_TEXT	ENDS
; Function compile flags: /Ogspy
_TEXT	SEGMENT
_hash$ = 8						; size = 4
?find_module@native@@YAPAXI@Z PROC			; native::find_module
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 13
	mov	eax, DWORD PTR fs:48
; Line 19
	push	esi
	push	edi
; Line 24
	mov	eax, DWORD PTR [eax+12]
	mov	esi, DWORD PTR [eax+12]
; Line 27
	mov	edi, esi
$LL4@find_modul:
; Line 33
	push	DWORD PTR [esi+48]
	call	??$r_hash@_W@@YAIPA_W@Z			; r_hash<wchar_t>
	pop	ecx
	cmp	eax, DWORD PTR _hash$[esp+4]
	je	SHORT $LN11@find_modul
; Line 37
	mov	esi, DWORD PTR [esi]
; Line 39
	test	esi, esi
	je	SHORT $LN6@find_modul
	cmp	esi, edi
	jne	SHORT $LL4@find_modul
$LN6@find_modul:
; Line 41
	xor	eax, eax
	jmp	SHORT $LN1@find_modul
$LN11@find_modul:
; Line 34
	mov	eax, DWORD PTR [esi+24]
$LN1@find_modul:
	pop	edi
; Line 42
	pop	esi
	ret	0
?find_module@native@@YAPAXI@Z ENDP			; native::find_module
_TEXT	ENDS
; Function compile flags: /Ogspy
;	COMDAT ?get_peb@native@@YAPAU_PEB@1@XZ
_TEXT	SEGMENT
?get_peb@native@@YAPAU_PEB@1@XZ PROC			; native::get_peb, COMDAT
; File E:\projects\_playground_\shellcode-test\shellcode-test\native.h
; Line 13
	mov	eax, DWORD PTR fs:48
; Line 15
	ret	0
?get_peb@native@@YAPAU_PEB@1@XZ ENDP			; native::get_peb
_TEXT	ENDS
END
